version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-comments
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: taskforce-comments
    ports:
      - 27018:27018
    volumes:
      - ./db:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-comments
    ports:
      - 8082:8082
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27018/
