# Create comment
POST http://localhost:3333/api/tasks/638589d7798f4804ac8ecfd0 HTTP/1.1
Content-Type: application/json

{
  "text": "          */*              "
}

###
# Get task comments
GET http://localhost:3333/api/tasks/638589d7798f4804ac8ecfd0/comments HTTP/1.1

###
# Delete task comments
DELETE http://localhost:3333/api/tasks/638589d7798f4804ac8ecfd0/comments HTTP/1.1

###
# Delete one comment
DELETE http://localhost:3333/api/tasks/638589d7798f4804ac8ecfd0/comments/638e27b94fe67ab3e91d9037 HTTP/1.1
