# Create task
POST http://localhost:3333/api/tasks/ HTTP/1.1
Content-Type: application/json

{
  "title": "Переехать в даль туманную",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius tortor nibh, sit amet tempor nibh finibus et. Aenean eu enim justo.",
  "category": "Перевозки",
  "address": "Владивосток, Тверская ул, дом 1",
  "userId": "6385bbbcc05cd5e757d37764",
  "tags": ["перевозки"],
  "commentsCount": 2
}

###
# Get tasks
GET http://localhost:3333/api/tasks/?tags=перевозки&sortType=responsesCount&sortDirection=asc HTTP/1.1

###
# Get task info
GET http://localhost:3333/api/tasks/2 HTTP/1.1

###
# Update task
PATCH http://localhost:3333/api/tasks/9?updateType=incCommentsCount HTTP/1.1
Content-Type: application/json


###
# Delete task
DELETE http://localhost:3333/api/tasks/7 HTTP/1.1
