# Create task
POST http://localhost:3330/api/tasks/ HTTP/1.1
Content-Type: application/json

{
  "title": "Задание для проверку смены статуса",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius tortor nibh, sit amet tempor nibh finibus et. Aenean eu enim justo.",
  "category": "Программирование",
  "address": "Москва, Тверская ул, дом 333",
  "customerId": "6385bbbcc05cd5e757d37764",
  "tags": ["RabbitMQ"],
  "deadline": "2024-01-20"
}

###
# Get tasks
GET http://localhost:3330/api/tasks/ HTTP/1.1

###
# Get new tasks
GET http://localhost:3330/api/tasks/new?tags=RabbitMQ&city=Владивосток HTTP/1.1

###
# Get task info
GET http://localhost:3330/api/tasks/7 HTTP/1.1

###
# Get personal tasks
GET http://localhost:3330/api/tasks/personal?status=AtWork HTTP/1.1
Content-Type: application/json

{
  "userId": "1234aaacc05cd5e757d37764",
  "userRole": "Исполнитель"
}

###
# Update task
PATCH http://localhost:3330/api/tasks/6 HTTP/1.1
Content-Type: application/json

{
  "address": "Санкт-Петербург, Тверская ул, дом 111",
}

###
# Change task status from New to AtWork
PATCH http://localhost:3330/api/tasks/7/status HTTP/1.1
Content-Type: application/json

{
  "newStatus": "AtWork",
  "customerId": "6385bbbcc05cd5e757d37764",
  "contractorId": "63ba8f0aa99e326258f2ea6a"
}

###
PATCH http://localhost:3330/api/tasks/6/status HTTP/1.1
Content-Type: application/json

{
  "newStatus": "Failed",
  "customerId": "6385bbbcc05cd5e757d37764",
  "contractorId": "6385bbbcc05cd5e757d37764"
}

###
# Add new response
PATCH http://localhost:3330/api/tasks/6/response HTTP/1.1
Content-Type: application/json

{
  "contractorId": "6385bbbcc05cd5e757d37764"
}

###
# Delete task
DELETE http://localhost:3330/api/tasks/4 HTTP/1.1

###
# Send new tasks on mail
GET http://localhost:3330/api/tasks/notify/ HTTP/1.1
Content-Type: application/json

{
  "email": "test2@gmail.com"
}

###
## Upload image for task
POST http://localhost:3330/api/tasks/1/image HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="task-image.jpg"
Content-Type: image/jpg

< task-image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

