version: '3.5'
services:
  fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: "fakesmtp"
    hostname: "fakesmtp"
    ports:
      - 5025:5025
      - 1084:5080

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 1085:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
