# Register user
POST http://localhost:3333/api/user/register HTTP/1.1
Content-Type: application/json

{
  "email": "qwerty123@mail.ru",
  "city": "Владивосток",
  "password": "123456",
  "birthDate": "2002-02-02",
  "role": "Исполнитель",
  "name": "Adsadsfasd"
}

###
# Login user
POST http://localhost:3333/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "qwerty123@mail.ru",
  "password": "123456"
}

###
# Get user info
GET http://localhost:3333/api/user/6385aaacc05cd5e757d37764 HTTP/1.1
