# Register user
POST http://localhost:3350/api/user/register HTTP/1.1
Content-Type: application/json

{
  "name": "Зыгмунд Зыгмунтович",
  "email": "test963@gmail.com",
  "city": "Москва",
  "password": "abcdefg",
  "role": "Исполнитель",
  "birthDate": "1993-01-01"
}

###
# @name login
POST http://localhost:3350/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "test900@gmail.com",
  "password": "123456"
}

###
@authToken = {{login.response.body.access_token}}

# Get user info
GET http://localhost:3350/api/user/63c31f12e0afa85f84aa73f2 HTTP/1.1
Authorization: Bearer {{authToken}}

###
# Change user password
PATCH http://localhost:3350/api/user/63c31f12e0afa85f84aa73f2/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "oldPassword": "abcdefg",
  "newPassword": "123456"
}

###
# Create user review
POST http://localhost:3350/api/user/review HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "customerId": "44dc1549485246c0e75315a9",
  "contractorId": "63c31f12e0afa85f84aa73f2",
  "taskId": 9,
  "reviewText": "He did such a great job and were quick and efficient. Also, our backyard is cleaner now than it was before they came! We would definitely recommend to anyone looking to have their roof replaced.",
  "reviewRating": 1
}

###
# Update user
PATCH http://localhost:3350/api/user/63c322e18ab55c27692d85ba HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "personalInfo": "A biography, or simply bio, is a detailed description of a person's life. It involves more than just the basic facts like education, work, relationships, and death; it portrays a person's experience of these life events.",
  "birthDate": "2002-01-01"
}

###
## Upload user avatar
POST http://localhost:3350/api/user/63c31f12e0afa85f84aa73f2/avatar HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpg

< /Desktop/avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
